let mainCan;
let bgImage;
let countDwn = 5;
let flyX = -10;
let flyY = 338;
let flyXR = -510;
let flyYR = 338;
let flyingBall;
let flyingTwo;
let flySpeed = 8
let Xcords = 63;
let secXCords = 441;
let ballStack = [];
let secondStack = [];
let manOne;
let manTwo;
let carrot;
let carrotTwo;
let hatOne;
let hatTwo;
let armOne;
let armBehindOne;
let armTwo;
let armBehindTwo;
let degOne = 380;
let degTwo = -200;
let swing = false;
let armSpeed = 20;
let startLeft = false;
let startRight = false;

